name: Revanced APKs

on:
  schedule:
    - cron: '*/60 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Revanced Youtube
        run: sh revanced youtube

      - name: Run Revanced Youtube Music
        run: sh revanced youtube-music

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: yt-*.apk
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "New Releases."
          
             
      - name: auwuto commit uwu
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update: New Version"
          repository: .
          file_pattern: track
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
